on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 18.20.4
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.4'
      
    - name: 🔨 Build Project
      run: |
        cd app
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USER}}
        password: ${{ secrets.FTP_PASSWORD }} 
